name: beyond
favicon: null
layout_spectrum: 0.5990306686144322
typography_spectrum: 0.5940573883708566
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5fbfb'
    - '#a5b4c7'
    - '#090909'
    - '#63cf18'
    - '#6581aa'
  brandStrength: 0.9796250096987933
  lightness: 0.6085015262942761
  saturation: 0.3440394261851907
  rhythmicContrast: 0.9319961408618838
purpose: []
